/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.BorderLayout;

/**
 *
 * @author User
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public Administrador() {
        initComponents();
        
        MenuPrincipal mp = new MenuPrincipal();
        mp.setSize(749,650);
        mp.setLocation(0,0);
        
        contenedor.removeAll();
        contenedor.add(mp,BorderLayout.CENTER);
        contenedor.validate();
        contenedor.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMenu = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnRSalidas = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnREntradas = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnREmpleados = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnInventario = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnProveedor = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnRProductos = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnSalir = new RSMaterialComponent.RSButtonMaterialIconDos();
        jSeparator1 = new javax.swing.JSeparator();
        btnReportes = new RSMaterialComponent.RSButtonMaterialIconDos();
        jLabel2 = new javax.swing.JLabel();
        contenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 0));

        jPanel2.setBackground(new java.awt.Color(102, 102, 0));

        jLabel1.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mirano");

        btnMenu.setBackground(new java.awt.Color(102, 102, 0));
        btnMenu.setText("Menú Principal");
        btnMenu.setBackgroundHover(new java.awt.Color(51, 51, 0));
        btnMenu.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HOME);
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnRSalidas.setBackground(new java.awt.Color(102, 102, 0));
        btnRSalidas.setText("Registrar salidas");
        btnRSalidas.setBackgroundHover(new java.awt.Color(51, 51, 0));
        btnRSalidas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LAUNCH);
        btnRSalidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRSalidasActionPerformed(evt);
            }
        });

        btnREntradas.setBackground(new java.awt.Color(102, 102, 0));
        btnREntradas.setText("Registrar entradas");
        btnREntradas.setBackgroundHover(new java.awt.Color(51, 51, 0));
        btnREntradas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_9_PLUS);
        btnREntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnREntradasActionPerformed(evt);
            }
        });

        btnREmpleados.setBackground(new java.awt.Color(102, 102, 0));
        btnREmpleados.setText("Registro de Empleados");
        btnREmpleados.setBackgroundHover(new java.awt.Color(51, 51, 0));
        btnREmpleados.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PEOPLE);
        btnREmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnREmpleadosActionPerformed(evt);
            }
        });

        btnInventario.setBackground(new java.awt.Color(102, 102, 0));
        btnInventario.setText("Iventario");
        btnInventario.setBackgroundHover(new java.awt.Color(51, 51, 0));
        btnInventario.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DNS);
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });

        btnProveedor.setBackground(new java.awt.Color(102, 102, 0));
        btnProveedor.setText("Proveedor / Compra");
        btnProveedor.setBackgroundHover(new java.awt.Color(51, 51, 0));
        btnProveedor.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DOMAIN);
        btnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorActionPerformed(evt);
            }
        });

        btnRProductos.setBackground(new java.awt.Color(102, 102, 0));
        btnRProductos.setText("Registro de productos");
        btnRProductos.setBackgroundHover(new java.awt.Color(51, 51, 0));
        btnRProductos.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PICTURE_IN_PICTURE);
        btnRProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRProductosActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(102, 102, 0));
        btnSalir.setText("Salir");
        btnSalir.setBackgroundHover(new java.awt.Color(51, 51, 0));
        btnSalir.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HIGHLIGHT_OFF);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnReportes.setBackground(new java.awt.Color(102, 102, 0));
        btnReportes.setText("Reportes");
        btnReportes.setBackgroundHover(new java.awt.Color(51, 51, 0));
        btnReportes.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EQUALIZER);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Reportes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnREmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                        .addComponent(btnProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnREntradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnRSalidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnRProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnREmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnREntradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRSalidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        contenedor.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 749, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        btnMenu.setSelected(true);
        btnREmpleados.setSelected(false);
        btnProveedor.setSelected(false);
        btnRProductos.setSelected(false);
        btnREntradas.setSelected(false);
        btnRSalidas.setSelected(false);
        btnInventario.setSelected(false);
        btnReportes.setSelected(false);
        
        MenuPrincipal mp = new MenuPrincipal();
        mp.setSize(749,650);
        mp.setLocation(0,0);
        
        contenedor.removeAll();
        contenedor.add(mp,BorderLayout.CENTER);
        contenedor.validate();
        contenedor.repaint();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnRSalidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRSalidasActionPerformed
        btnMenu.setSelected(false);
        btnREmpleados.setSelected(false);
        btnProveedor.setSelected(false);
        btnRProductos.setSelected(false);
        btnREntradas.setSelected(false);
        btnRSalidas.setSelected(true);
        btnInventario.setSelected(false);
        btnReportes.setSelected(false);
        
        Salidas sa = new Salidas();
        sa.setSize(749,650);
        sa.setLocation(0,0);
        
        contenedor.removeAll();
        contenedor.add(sa,BorderLayout.CENTER);
        contenedor.validate();
        contenedor.repaint();
    }//GEN-LAST:event_btnRSalidasActionPerformed

    private void btnREntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnREntradasActionPerformed
        btnMenu.setSelected(false);
        btnREmpleados.setSelected(false);
        btnProveedor.setSelected(false);
        btnRProductos.setSelected(false);
        btnREntradas.setSelected(true);
        btnRSalidas.setSelected(false);
        btnInventario.setSelected(false);
        btnReportes.setSelected(false);
        
        Entradas en = new Entradas();
        en.setSize(749,650);
        en.setLocation(0,0);
        
        contenedor.removeAll();
        contenedor.add(en,BorderLayout.CENTER);
        contenedor.validate();
        contenedor.repaint();
    }//GEN-LAST:event_btnREntradasActionPerformed

    private void btnREmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnREmpleadosActionPerformed
        btnMenu.setSelected(false);
        btnREmpleados.setSelected(true);
        btnProveedor.setSelected(false);
        btnRProductos.setSelected(false);
        btnREntradas.setSelected(false);
        btnRSalidas.setSelected(false);
        btnInventario.setSelected(false);
        btnReportes.setSelected(false);
        
        RegistroEmpleados re = new RegistroEmpleados();
        re.setSize(749,650);
        re.setLocation(0,0);
        
        contenedor.removeAll();
        contenedor.add(re,BorderLayout.CENTER);
        contenedor.validate();
        contenedor.repaint();
    }//GEN-LAST:event_btnREmpleadosActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        btnMenu.setSelected(false);
        btnREmpleados.setSelected(false);
        btnProveedor.setSelected(false);
        btnRProductos.setSelected(false);
        btnREntradas.setSelected(false);
        btnRSalidas.setSelected(false);
        btnInventario.setSelected(true);
        btnReportes.setSelected(false);
        
        ViewInventario vi = new ViewInventario();
        vi.setSize(749,650);
        vi.setLocation(0,0);
        
        contenedor.removeAll();
        contenedor.add(vi,BorderLayout.CENTER);
        contenedor.validate();
        contenedor.repaint();
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorActionPerformed
        btnMenu.setSelected(false);
        btnREmpleados.setSelected(false);
        btnProveedor.setSelected(true);
        btnRProductos.setSelected(false);
        btnREntradas.setSelected(false);
        btnRSalidas.setSelected(false);
        btnInventario.setSelected(false);
        btnReportes.setSelected(false);
        
        ProveedorCompra pc = new ProveedorCompra();
        pc.setSize(749,650);
        pc.setLocation(0,0);
        
        contenedor.removeAll();
        contenedor.add(pc,BorderLayout.CENTER);
        contenedor.validate();
        contenedor.repaint();
    }//GEN-LAST:event_btnProveedorActionPerformed

    private void btnRProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRProductosActionPerformed
        btnMenu.setSelected(false);
        btnREmpleados.setSelected(false);
        btnProveedor.setSelected(false);
        btnRProductos.setSelected(true);
        btnREntradas.setSelected(false);
        btnRSalidas.setSelected(false);
        btnInventario.setSelected(false);
        btnReportes.setSelected(false);
        
        RegistrarProductos rp = new RegistrarProductos();
        rp.setSize(749,650);
        rp.setLocation(0,0);
        
        contenedor.removeAll();
        contenedor.add(rp,BorderLayout.CENTER);
        contenedor.validate();
        contenedor.repaint();
    }//GEN-LAST:event_btnRProductosActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        Login lg = new Login();
        lg.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        btnMenu.setSelected(false);
        btnREmpleados.setSelected(false);
        btnProveedor.setSelected(false);
        btnRProductos.setSelected(false);
        btnREntradas.setSelected(false);
        btnRSalidas.setSelected(false);
        btnInventario.setSelected(false);
        btnReportes.setSelected(true);
        
        Reportes re = new Reportes();
        re.setSize(749,650);
        re.setLocation(0,0);
        
        contenedor.removeAll();
        contenedor.add(re,BorderLayout.CENTER);
        contenedor.validate();
        contenedor.repaint();
    }//GEN-LAST:event_btnReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconDos btnInventario;
    private RSMaterialComponent.RSButtonMaterialIconDos btnMenu;
    private RSMaterialComponent.RSButtonMaterialIconDos btnProveedor;
    private RSMaterialComponent.RSButtonMaterialIconDos btnREmpleados;
    private RSMaterialComponent.RSButtonMaterialIconDos btnREntradas;
    private RSMaterialComponent.RSButtonMaterialIconDos btnRProductos;
    private RSMaterialComponent.RSButtonMaterialIconDos btnRSalidas;
    private RSMaterialComponent.RSButtonMaterialIconDos btnReportes;
    private RSMaterialComponent.RSButtonMaterialIconDos btnSalir;
    private javax.swing.JPanel contenedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
