/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.DaoCategorias;
import controlador.DaoProductos;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.plaf.RootPaneUI;
import javax.swing.table.DefaultTableModel;
import modelo.Categorias;
import modelo.Productos;

/**
 *
 * @author User
 */
public class RegistrarProductos extends javax.swing.JPanel {

    //instanciar la clase Categorias
    Categorias ct = new Categorias();
    DaoCategorias daoC = new DaoCategorias();
    //instanciar la clase productos
    Productos pr = new Productos();
    DaoProductos daoP = new DaoProductos();
    
    // mostrar datos en la tabla categorias
    DefaultTableModel modeloCategoria = new DefaultTableModel();
    // mostrar datos en la tabla productos
    DefaultTableModel modeloProductos = new DefaultTableModel();
    
    public RegistrarProductos() {
        initComponents();
        listarCategorias();
        listarProductos();
    }
    
    private void listarCategorias(){
        List<Categorias> listaC = daoC.Listar();
        modeloCategoria = (DefaultTableModel) tblCategorias.getModel();
        Object[] ob = new Object[2];
        for(int i=0; i< listaC.size(); i++){
            ob[0] = listaC.get(i).getId_categoria();
            ob[1] = listaC.get(i).getNombre_categoria();
            modeloCategoria.addRow(ob);
        }
        tblCategorias.setModel(modeloCategoria);
    }
    private void listarProductos(){
        List<Productos> listaP = daoP.Listar();
        modeloProductos = (DefaultTableModel) tblProductos.getModel();
        Object[] ob = new Object[6];
        for(int i=0; i< listaP.size(); i++){
            ob[0] = listaP.get(i).getId_producto();
            ob[1] = listaP.get(i).getNombre_producto();
            ob[2] = listaP.get(i).getMarca();
            ob[3] = listaP.get(i).getDescripcion();
            ob[4] = listaP.get(i).getId_categoria();
            ob[5] = listaP.get(i).getStock_minimo();
            modeloProductos.addRow(ob);
        }
        tblProductos.setModel(modeloProductos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtIdP = new javax.swing.JTextField();
        txtNomP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMarcaP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtIdC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDesP = new javax.swing.JTextField();
        btnGuardarC1 = new RSMaterialComponent.RSButtonMaterialIconDos();
        jLabel12 = new javax.swing.JLabel();
        txtStockM = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        btnBuscarP = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnEliminarP = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnEditarPro = new RSMaterialComponent.RSButtonMaterialIconDos();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtIdCat = new javax.swing.JTextField();
        txtNomCat = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnGuardarC = new RSMaterialComponent.RSButtonMaterialIconDos();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblCategorias = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        txtEditarCat = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnBuscarC = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnEliminarC = new RSMaterialComponent.RSButtonMaterialIconDos();

        setBackground(new java.awt.Color(204, 243, 146));

        jLabel4.setFont(new java.awt.Font("SimSun-ExtG", 1, 24)); // NOI18N
        jLabel4.setText("Productos");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("ID del producto");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Nombre del producto");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Marca del producto");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("ID de la categoria del producto");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Descripción del producto");

        btnGuardarC1.setText("Guardar");
        btnGuardarC1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        btnGuardarC1.setRound(25);
        btnGuardarC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarC1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("Stock Minimo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(txtStockM, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardarC1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDesP, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtIdC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(txtMarcaP, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomP, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdP, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 58, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNomP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMarcaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(5, 5, 5)
                .addComponent(txtDesP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardarC1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStockM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_producto", "nombre_producto", "marca", "descripcion", "id_categoria", "stock_minimo"
            }
        ));
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProductos);

        btnBuscarP.setBackground(new java.awt.Color(0, 204, 51));
        btnBuscarP.setText("Buscar");
        btnBuscarP.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        btnBuscarP.setRound(25);
        btnBuscarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPActionPerformed(evt);
            }
        });

        btnEliminarP.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminarP.setText("Eliminar");
        btnEliminarP.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        btnEliminarP.setRound(25);
        btnEliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPActionPerformed(evt);
            }
        });

        btnEditarPro.setBackground(new java.awt.Color(204, 204, 0));
        btnEditarPro.setText("Editar");
        btnEditarPro.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        btnEditarPro.setRound(25);
        btnEditarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnEditarPro, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarP, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarP, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarPro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarP, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarP, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("SimSun-ExtG", 1, 24)); // NOI18N
        jLabel10.setText("Categoria del Producto");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("ID de la categoría");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText("Nombre de la categoría");

        btnGuardarC.setText("Guardar");
        btnGuardarC.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        btnGuardarC.setRound(25);
        btnGuardarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomCat)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtIdCat, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 149, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarC, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarC, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(375, 375, 375))
        );

        tblCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_categoria", "nombre_categoria"
            }
        ));
        tblCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCategoriasMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblCategorias);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtEditarCat.setBackground(new java.awt.Color(204, 204, 0));
        txtEditarCat.setText("Editar");
        txtEditarCat.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        txtEditarCat.setRound(25);
        txtEditarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditarCatActionPerformed(evt);
            }
        });

        btnBuscarC.setBackground(new java.awt.Color(0, 204, 51));
        btnBuscarC.setText("Buscar");
        btnBuscarC.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        btnBuscarC.setRound(25);
        btnBuscarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCActionPerformed(evt);
            }
        });

        btnEliminarC.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminarC.setText("Eliminar");
        btnEliminarC.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        btnEliminarC.setRound(25);
        btnEliminarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEditarCat, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscarC, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminarC, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel10)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEditarCat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarC, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarC, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCActionPerformed
        //verificar el llenado
        if (txtNomCat.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor llene el nombre de la categoria");
            return;
        }
        
        ct.setNombre_categoria(txtNomCat.getText());
        if(daoC.insert(ct)){
            if(!txtIdCat.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "No es necesario poner el ID de la categoria, el sistema lo asigna automáticamente");
            }
            JOptionPane.showMessageDialog(null, "Categoria Registrada");
        }else {
            JOptionPane.showMessageDialog(null, "No se pudo registrar la categoria");
        }
        limpiarCamposCat();
        limpiarTablaCategorias();
        listarCategorias();
    }//GEN-LAST:event_btnGuardarCActionPerformed

    private void btnGuardarC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarC1ActionPerformed
        // Validar que los campos no estén vacíos
        if (txtNomP.getText().isEmpty() || txtMarcaP.getText().isEmpty() || txtDesP.getText().isEmpty() || txtIdC.getText().isEmpty() || txtStockM.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor complete todos los campos.");
            return;
        }

        // Validar que el ID de categoría y el stock sea un número
        int idCategoria;
        int stockM;
        try {
            idCategoria = Integer.parseInt(txtIdC.getText());
            stockM = Integer.parseInt(txtStockM.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El ID de categoría y el stock minimo debe ser un número.");
            return;
        }
        //
        pr.setNombre_producto(txtNomP.getText());
        pr.setMarca(txtMarcaP.getText());
        pr.setDescripcion(txtDesP.getText());
        pr.setId_categoria(Integer.parseInt(txtIdC.getText()));
        pr.setStock_minimo(Integer.parseInt(txtStockM.getText()));
        
        if(daoP.insert(pr)){
            //informar que el Id producto es autoasignado por el sistema
            if(!txtIdP.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "No es necesario poner el ID del producto, el sistema lo asigna automáticamente");
            }
            JOptionPane.showMessageDialog(null, "Producto Registrado");
        }else {
            JOptionPane.showMessageDialog(null, "No se pudo registrar el producto");
        }
        limpiarCamposPro();
        limpiarTablaProductos();
        listarProductos();
    }//GEN-LAST:event_btnGuardarC1ActionPerformed

    private void txtEditarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditarCatActionPerformed
        int fila = tblCategorias.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(null, "Seleccione una categoria");
        }else{
            ct.setId_categoria(Integer.parseInt(txtIdCat.getText()));
            ct.setNombre_categoria(txtNomCat.getText());
            if(daoC.editar(ct)){
                JOptionPane.showMessageDialog(null, "Se modifico con exito");
                limpiarCamposCat();
                limpiarTablaCategorias();
                listarCategorias();
            }
        }
    }//GEN-LAST:event_txtEditarCatActionPerformed

    private void btnBuscarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCActionPerformed
        ct.setId_categoria(Integer.parseInt(txtIdCat.getText()));
        if(daoC.buscar(ct)){
            txtIdCat.setText(ct.getId_categoria()+"");
            txtNomCat.setText(ct.getNombre_categoria());
        }else{
            JOptionPane.showMessageDialog(null, "La categoria no existe");
            limpiarCamposCat();
        }
    }//GEN-LAST:event_btnBuscarCActionPerformed

    private void btnEliminarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCActionPerformed
        if(!txtIdCat.getText().isEmpty()){
            int confirmacion = JOptionPane.showConfirmDialog(null, "Estas seguro de eliminar la Categoria","Confirmar",2);
            if(confirmacion == 0){
                ct.setId_categoria(Integer.parseInt(txtIdCat.getText()));
                daoC.eliminar(ct);
                limpiarCamposCat();
                limpiarTablaCategorias();
                listarCategorias();
                JOptionPane.showMessageDialog(null, "Se elimino la categoria");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione una categoria");
        }
    }//GEN-LAST:event_btnEliminarCActionPerformed

    private void btnEditarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProActionPerformed
        int fila = tblProductos.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(null, "Seleccione un producto");
        }else{
            pr.setId_producto(Integer.parseInt(txtIdP.getText()));
            pr.setNombre_producto(txtNomP.getText());
            pr.setMarca(txtMarcaP.getText());
            pr.setDescripcion(txtDesP.getText());
            pr.setId_categoria(Integer.parseInt(txtIdC.getText()));
            pr.setStock_minimo(Integer.parseInt(txtStockM.getText()));
            if(daoP.editar(pr)){
                JOptionPane.showMessageDialog(null, "Se modifico con exito");
                limpiarCamposPro();
                limpiarTablaProductos();
                listarProductos();
            }
        }
    }//GEN-LAST:event_btnEditarProActionPerformed

    private void btnBuscarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPActionPerformed
        pr.setId_producto(Integer.parseInt(txtIdP.getText()));
        if(daoP.buscar(pr)){
            txtIdP.setText(pr.getId_producto()+"");
            txtNomP.setText(pr.getNombre_producto());
            txtMarcaP.setText(pr.getMarca());
            txtDesP.setText(pr.getDescripcion());
            txtIdC.setText(pr.getId_categoria()+"");
            txtStockM.setText(pr.getStock_minimo()+"");
        }else{
            JOptionPane.showMessageDialog(null, "La categoria no existe");
            limpiarCamposPro();
        }
    }//GEN-LAST:event_btnBuscarPActionPerformed

    private void btnEliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPActionPerformed
        if(!txtIdP.getText().isEmpty()){
            int confirmacion = JOptionPane.showConfirmDialog(null, "Estas seguro de eliminar el producto","Confirmar",2);
            if(confirmacion == 0){
                pr.setId_producto(Integer.parseInt(txtIdP.getText()));
                daoP.eliminar(pr);
                limpiarCamposPro();
                limpiarTablaProductos();
                listarProductos();
                JOptionPane.showMessageDialog(null, "Se elimino el producto");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione el ID del producto");
        }
    }//GEN-LAST:event_btnEliminarPActionPerformed

    private void tblCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCategoriasMouseClicked
        int fila = tblCategorias.getSelectedRow();
        txtIdCat.setText(tblCategorias.getValueAt(fila, 0).toString());
        txtNomCat.setText(tblCategorias.getValueAt(fila, 1).toString());
    }//GEN-LAST:event_tblCategoriasMouseClicked

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        int fila = tblProductos.getSelectedRow();
        txtIdP.setText(tblProductos.getValueAt(fila, 0).toString());
        txtNomP.setText(tblProductos.getValueAt(fila, 1).toString());
        txtMarcaP.setText(tblProductos.getValueAt(fila, 2).toString());
        txtDesP.setText(tblProductos.getValueAt(fila, 3).toString());
        txtIdC.setText(tblProductos.getValueAt(fila, 4).toString());
        txtStockM.setText(tblProductos.getValueAt(fila, 5).toString());
    }//GEN-LAST:event_tblProductosMouseClicked

    void limpiarCamposCat(){
        txtIdCat.setText("");
        txtNomCat.setText("");
    }
    void limpiarCamposPro(){
        txtIdP.setText("");
        txtNomP.setText("");
        txtMarcaP.setText("");
        txtDesP.setText("");
        txtIdC.setText("");        
        txtStockM.setText("");        
    }
    void limpiarTablaCategorias(){
        for(int i=0; i<modeloCategoria.getRowCount();i++){
            modeloCategoria.removeRow(i);
            i = 0-1;
        }
    }
    void limpiarTablaProductos(){
        for(int i=0; i<modeloProductos.getRowCount();i++){
            modeloProductos.removeRow(i);
            i = 0-1;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconDos btnBuscarC;
    private RSMaterialComponent.RSButtonMaterialIconDos btnBuscarP;
    private RSMaterialComponent.RSButtonMaterialIconDos btnEditarPro;
    private RSMaterialComponent.RSButtonMaterialIconDos btnEliminarC;
    private RSMaterialComponent.RSButtonMaterialIconDos btnEliminarP;
    private RSMaterialComponent.RSButtonMaterialIconDos btnGuardarC;
    private RSMaterialComponent.RSButtonMaterialIconDos btnGuardarC1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblCategorias;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtDesP;
    private RSMaterialComponent.RSButtonMaterialIconDos txtEditarCat;
    private javax.swing.JTextField txtIdC;
    private javax.swing.JTextField txtIdCat;
    private javax.swing.JTextField txtIdP;
    private javax.swing.JTextField txtMarcaP;
    private javax.swing.JTextField txtNomCat;
    private javax.swing.JTextField txtNomP;
    private javax.swing.JTextField txtStockM;
    // End of variables declaration//GEN-END:variables
}
