/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.DaoEntradas;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import modelo.Entradas;

/**
 *
 * @author User
 */
public class RegistroEntradas extends javax.swing.JPanel {

    // instaciar la clase y el dao de entradas
    Entradas en = new Entradas();
    DaoEntradas daoEn = new DaoEntradas();
    // mostrar datos en la tabla compra
    DefaultTableModel modeloEntrada = new DefaultTableModel();
    
    public RegistroEntradas() {
        initComponents();
        listarEntradas();
    }
    
    private void listarEntradas(){
        List<Entradas> listaEn = daoEn.Listar();
        modeloEntrada = (DefaultTableModel) tblEntradas.getModel();
        Object[] ob = new Object[9];
        for(int i=0; i< listaEn.size(); i++){
            ob[0] = listaEn.get(i).getId_entrada();
            ob[1] = listaEn.get(i).getId_compra();
            ob[2] = listaEn.get(i).getId_usuario();
            ob[3] = listaEn.get(i).getId_producto();
            ob[4] = listaEn.get(i).getTipo_unidad();
            ob[5] = listaEn.get(i).getCantidad();
            ob[6] = listaEn.get(i).getCosto_unit();
            ob[7] = listaEn.get(i).getFecha_vencimiento();
            ob[8] = listaEn.get(i).getFecha_entrada();
            
            
            modeloEntrada.addRow(ob);
        }
        tblEntradas.setModel(modeloEntrada);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEntradas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdEn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIdCom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIdUs = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIdPro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFe = new javax.swing.JTextField();
        btnGuardarEn = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnEditarE = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnBuscarE = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnEliminarE = new RSMaterialComponent.RSButtonMaterialIconDos();
        jLabel10 = new javax.swing.JLabel();
        txtFeE = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 243, 146));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        tblEntradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_entrada", "id_compra", "id_usuario", "id_producto", "tipo_unidad", "cantidad", "costo_unit", "fecha_vencimiento", "fecha_entrada"
            }
        ));
        tblEntradas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEntradasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEntradas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel1.setText("Entradas");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("ID Entrada:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("ID Compra:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("ID Usuario:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("ID Producto:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Tipo de unidad:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Cantidad:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Costo Unitario:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Fecha de Vencimiento:");

        btnGuardarEn.setText("Guardar");
        btnGuardarEn.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        btnGuardarEn.setRound(25);
        btnGuardarEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEnActionPerformed(evt);
            }
        });

        btnEditarE.setBackground(new java.awt.Color(204, 204, 0));
        btnEditarE.setText("Editar");
        btnEditarE.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        btnEditarE.setRound(25);
        btnEditarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEActionPerformed(evt);
            }
        });

        btnBuscarE.setBackground(new java.awt.Color(0, 204, 0));
        btnBuscarE.setText("Buscar");
        btnBuscarE.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        btnBuscarE.setRound(25);
        btnBuscarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEActionPerformed(evt);
            }
        });

        btnEliminarE.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminarE.setText("Eliminar");
        btnEliminarE.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE_SWEEP);
        btnEliminarE.setRound(25);
        btnEliminarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Fecha de Entrada:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(txtIdEn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdCom, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(txtIdUs, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtIdPro, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(46, 46, 46)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(txtCan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtFeE, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtFe))))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditarE, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarEn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnBuscarE, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarE, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFeE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtIdEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEActionPerformed
        // if agregado
        if(txtIdEn.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese el ID de la entrada");
            limpiarCamposEn();
            return;
        }
        //
        en.setId_entrada(Integer.parseInt(txtIdEn.getText()));
        if(daoEn.buscar(en)){
            txtIdEn.setText(en.getId_entrada()+"");
            txtIdCom.setText(en.getId_compra()+"");
            txtIdUs.setText(en.getId_usuario()+"");
            txtIdPro.setText(en.getId_producto()+"");
            txtTipo.setText(en.getTipo_unidad());
            txtCan.setText(en.getCantidad()+"");
            txtCos.setText(en.getCosto_unit()+"");
            txtFe.setText(en.getFecha_vencimiento()+"");
            txtFeE.setText(en.getFecha_entrada()+"");
            
        }else{
            JOptionPane.showMessageDialog(null, "La entrada no existe");
            limpiarCamposEn();
        }
    }//GEN-LAST:event_btnBuscarEActionPerformed

    private void btnEliminarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEActionPerformed
        if(!txtIdEn.getText().isEmpty()){
            int confirmacion = JOptionPane.showConfirmDialog(null, "Estas seguro de eliminar la entrada","Confirmar",2);
            if(confirmacion == 0){
                en.setId_entrada(Integer.parseInt(txtIdEn.getText()));
                daoEn.eliminar(en);
                limpiarCamposEn();
                limpiarTablaEntrada();
                listarEntradas();
                JOptionPane.showMessageDialog(null, "Se elimino la entrada");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione el ID de entrada");
        }
    }//GEN-LAST:event_btnEliminarEActionPerformed

    private void btnGuardarEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEnActionPerformed
        // Validar que los campos no estén vacíos
        if (txtIdCom.getText().isEmpty() ||txtIdUs.getText().isEmpty() ||txtIdPro.getText().isEmpty() ||txtTipo.getText().isEmpty() ||txtCan.getText().isEmpty() ||txtCos.getText().isEmpty() || txtFe.getText().isEmpty()|| txtFeE.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor complete todos los campos.");
            return;
        }

        // Validar que el ID de sea un numero
        int idCom;
        int idUs;
        int idPro;
       
        try {
            idCom = Integer.parseInt(txtIdCom.getText());            
            idUs = Integer.parseInt(txtIdUs.getText());            
            idPro = Integer.parseInt(txtIdPro.getText());            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El ID de compra, usuario y producto debe ser un número.");
            return;
        }
        //validar la fecha
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate FechaV;
        LocalDate FechaE;
        try {            
            FechaV = LocalDate.parse(txtFe.getText(),formatter);
            FechaE = LocalDate.parse(txtFeE.getText(),formatter);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(null, "La fecha debe estar en formato yyyy-MM-dd.");
            return;
        }
        //
        
        en.setId_compra(Integer.parseInt(txtIdCom.getText()));
        en.setId_usuario(Integer.parseInt(txtIdUs.getText()));
        en.setId_producto(Integer.parseInt(txtIdPro.getText()));
        en.setTipo_unidad(txtTipo.getText());
        en.setCantidad(Integer.parseInt(txtCan.getText()));
        en.setCosto_unit(Double.parseDouble(txtCos.getText()));
        en.setFecha_vencimiento(LocalDate.parse(txtFe.getText(),formatter));
        en.setFecha_entrada(LocalDate.parse(txtFeE.getText(),formatter));
        
        
        if(daoEn.insert(en)){
            //informar que el Id compra es autoasignado por el sistema
            if(!txtIdEn.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "No es necesario poner el ID de entrada, el sistema lo asigna automáticamente");
            }
            JOptionPane.showMessageDialog(null, "Entrada Registrada");
        }else {
            JOptionPane.showMessageDialog(null, "No se pudo registrar la entrada");
        }
        limpiarCamposEn();
        limpiarTablaEntrada();
        listarEntradas();
    
    }//GEN-LAST:event_btnGuardarEnActionPerformed

    private void tblEntradasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEntradasMouseClicked
        int fila = tblEntradas.getSelectedRow();
        txtIdEn.setText(tblEntradas.getValueAt(fila, 0).toString());
        txtIdCom.setText(tblEntradas.getValueAt(fila, 1).toString());
        txtIdUs.setText(tblEntradas.getValueAt(fila, 2).toString());
        txtIdPro.setText(tblEntradas.getValueAt(fila, 3).toString());        
        txtTipo.setText(tblEntradas.getValueAt(fila, 4).toString());       
        txtCan.setText(tblEntradas.getValueAt(fila, 5).toString());
        txtCos.setText(tblEntradas.getValueAt(fila, 6).toString());
        txtFe.setText(tblEntradas.getValueAt(fila, 7).toString());
        txtFeE.setText(tblEntradas.getValueAt(fila, 8).toString());
        
        
    }//GEN-LAST:event_tblEntradasMouseClicked

    private void btnEditarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEActionPerformed
        int fila = tblEntradas.getSelectedRow();
        //validar la fecha
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        
        if(fila==-1){
            JOptionPane.showMessageDialog(null, "Seleccione un producto");
        }else{
            en.setId_entrada(Integer.parseInt(txtIdEn.getText()));
            en.setId_compra(Integer.parseInt(txtIdCom.getText()));
            en.setId_usuario(Integer.parseInt(txtIdUs.getText()));
            en.setId_producto(Integer.parseInt(txtIdPro.getText()));
            en.setTipo_unidad(txtTipo.getText());
            en.setCantidad(Integer.parseInt(txtCan.getText()));
            en.setCosto_unit(Double.parseDouble(txtCos.getText()));
            en.setFecha_vencimiento(LocalDate.parse(txtFe.getText(),formatter));
            en.setFecha_entrada(LocalDate.parse(txtFeE.getText(),formatter));
            
            if(daoEn.editar(en)){
                JOptionPane.showMessageDialog(null, "Se modifico con exito");
                limpiarCamposEn();
                limpiarTablaEntrada();
                listarEntradas();
            }
        }
    }//GEN-LAST:event_btnEditarEActionPerformed
    
    void limpiarCamposEn(){
        txtIdEn.setText("");
        txtIdUs.setText("");
        txtIdCom.setText("");
        txtIdPro.setText("");
        txtTipo.setText("");
        txtCan.setText("");
        txtCos.setText("");
        txtFe.setText("");
        txtFeE.setText("");
        
    }
    void limpiarTablaEntrada(){
        for(int i=0; i<modeloEntrada.getRowCount();i++){
            modeloEntrada.removeRow(i);
            i = 0-1;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconDos btnBuscarE;
    private RSMaterialComponent.RSButtonMaterialIconDos btnEditarE;
    private RSMaterialComponent.RSButtonMaterialIconDos btnEliminarE;
    private RSMaterialComponent.RSButtonMaterialIconDos btnGuardarEn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEntradas;
    private javax.swing.JTextField txtCan;
    private javax.swing.JTextField txtCos;
    private javax.swing.JTextField txtFe;
    private javax.swing.JTextField txtFeE;
    private javax.swing.JTextField txtIdCom;
    private javax.swing.JTextField txtIdEn;
    private javax.swing.JTextField txtIdPro;
    private javax.swing.JTextField txtIdUs;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
