/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import controlador.DaoSalidas;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import modelo.Salidas;
import modelo.conexion;

/**
 *
 * @author User
 */
public class RegistroSalidas extends javax.swing.JPanel {

    conexion cn = new conexion();
// instaciar la clase y el dao de entradas
    Salidas sa = new Salidas();
    DaoSalidas daoSa = new DaoSalidas();
    // mostrar datos en la tabla compra
    DefaultTableModel modeloSalida = new DefaultTableModel();
    
    public RegistroSalidas() {
        initComponents();
        listarSalidas();
    }
    
    private void listarSalidas(){
        List<Salidas> listaSa = daoSa.Listar();
        modeloSalida = (DefaultTableModel) tblSalida.getModel();
        Object[] ob = new Object[8];
        for(int i=0; i< listaSa.size(); i++){
            ob[0] = listaSa.get(i).getId_salida();
            ob[1] = listaSa.get(i).getId_usuario();
            ob[2] = listaSa.get(i).getId_producto();
            ob[3] = listaSa.get(i).getTipo_unidad();
            ob[4] = listaSa.get(i).getCantidad();
            ob[5] = listaSa.get(i).getCosto_unit();
            ob[6] = listaSa.get(i).getFecha_salida();
            ob[7] = listaSa.get(i).getMotivo_salida();
            
            
            modeloSalida.addRow(ob);
        }
        tblSalida.setModel(modeloSalida);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSalida = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdSa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIdUs = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIdP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFe = new javax.swing.JTextField();
        btnGuardarS = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnEditarS = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnBuscarS = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnEliminarS = new RSMaterialComponent.RSButtonMaterialIconDos();
        jLabel10 = new javax.swing.JLabel();
        cboM = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(204, 243, 146));

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));

        tblSalida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_salida", "id_usuario", "id_producto", "tipo_unidad", "cantidad", "costo_unit", "fecha_salida", "motivo_salida"
            }
        ));
        tblSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSalidaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSalida);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel1.setText("Salidas");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("ID Salida:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("ID Usuario:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("ID Producto:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Cantidad:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Fecha de Vencimiento:");

        btnGuardarS.setText("Guardar");
        btnGuardarS.setRound(25);
        btnGuardarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarSActionPerformed(evt);
            }
        });

        btnEditarS.setBackground(new java.awt.Color(204, 204, 0));
        btnEditarS.setText("Editar");
        btnEditarS.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        btnEditarS.setRound(25);
        btnEditarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarSActionPerformed(evt);
            }
        });

        btnBuscarS.setBackground(new java.awt.Color(0, 204, 0));
        btnBuscarS.setText("Buscar");
        btnBuscarS.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        btnBuscarS.setRound(25);
        btnBuscarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarSActionPerformed(evt);
            }
        });

        btnEliminarS.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminarS.setText("Eliminar");
        btnEliminarS.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE_SWEEP);
        btnEliminarS.setRound(25);
        btnEliminarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Motivo de salida:");

        cboM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ventas", "vencimiento", "otros" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtIdSa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtIdP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtCan, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFe, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(cboM, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditarS, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarS, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnBuscarS, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarS, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdSa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cboM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnGuardarS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditarS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnBuscarS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEliminarS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarSActionPerformed
        // if agregado
        if(txtIdSa.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese el ID de la salida");
            limpiarCamposSa();
            return;
        }
        //
        sa.setId_salida(Integer.parseInt(txtIdSa.getText()));
        if(daoSa.buscar(sa)){
            txtIdSa.setText(sa.getId_salida()+"");
            txtIdUs.setText(sa.getId_usuario()+"");
            txtIdP.setText(sa.getId_producto()+"");
            txtCan.setText(sa.getCantidad()+"");
            txtFe.setText(sa.getFecha_salida()+"");
            cboM.setSelectedItem(sa.getMotivo_salida());
            
        }else{
            JOptionPane.showMessageDialog(null, "La salida no existe");
            limpiarCamposSa();
        }
    }//GEN-LAST:event_btnBuscarSActionPerformed

    private void btnEliminarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarSActionPerformed
        if(!txtIdSa.getText().isEmpty()){
            int confirmacion = JOptionPane.showConfirmDialog(null, "Estas seguro de eliminar la salida","Confirmar",2);
            if(confirmacion == 0){
                sa.setId_salida(Integer.parseInt(txtIdSa.getText()));
                daoSa.eliminar(sa);
                limpiarCamposSa();
                limpiarTablaSalidas();
                listarSalidas();
                JOptionPane.showMessageDialog(null, "Se elimino la salida");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione el ID de la salida");
        }
    }//GEN-LAST:event_btnEliminarSActionPerformed

    private void btnGuardarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarSActionPerformed
        // Validar que los campos no estén vacíos
        if (txtIdUs.getText().isEmpty() ||txtIdP.getText().isEmpty()||txtCan.getText().isEmpty() || txtFe.getText().isEmpty()||cboM.getSelectedItem().toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor complete todos los campos.");
            return;
        }

        // Validar que el ID de sea un numero
        
        int idUs;
        int idPro;
       
        try {
                       
            idUs = Integer.parseInt(txtIdUs.getText());            
            idPro = Integer.parseInt(txtIdP.getText());            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El ID de usuario y producto debe ser un número.");
            return;
        }
        //validar la fecha
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate FechaS;
        try {            
            FechaS = LocalDate.parse(txtFe.getText(),formatter);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(null, "La fecha debe estar en formato dd/MM/yyyy.");
            return;
        }
        //
               
        sa.setId_usuario(Integer.parseInt(txtIdUs.getText()));
        sa.setId_producto(Integer.parseInt(txtIdP.getText()));
        //sa.setTipo_unidad(txtTipo.getText());
        sa.setCantidad(Integer.parseInt(txtCan.getText()));
        //sa.setCosto_unit(Double.parseDouble(txtCo.getText()));
        sa.setFecha_salida(LocalDate.parse(txtFe.getText(),formatter));
        sa.setMotivo_salida(cboM.getSelectedItem().toString());
        
        // Consulta para obtener tipo_unidad y costo_unit desde la tabla entradas
        String selectEntradaSQL = "SELECT tipo_unidad, costo_unit FROM entradas WHERE id_producto = ? ORDER BY id_entrada ASC LIMIT 1";

        try (Connection con = cn.conectar();
         PreparedStatement ps = con.prepareStatement(selectEntradaSQL)) {

        ps.setInt(1, sa.getId_producto());
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            String tipoUnidad = rs.getString("tipo_unidad");
            double costoUnit = rs.getDouble("costo_unit");

            sa.setTipo_unidad(tipoUnidad);
            sa.setCosto_unit(costoUnit);

            // Opcional: mostrar los valores en los campos para que el usuario los vea
            /*txtTipo.setText(tipoUnidad);
            txtTipo.setEditable(false); // evitar que el usuario lo modifique
            txtCo.setText(String.valueOf(costoUnit));
            txtCo.setEditable(false);*/

        } else {
            JOptionPane.showMessageDialog(null, "No se encontró información en 'entradas' para el producto con ID: " + sa.getId_producto());
            return; // detener ejecución si no hay datos para completar
        }

        // Llamar al método insert ya con todos los datos completos
        if (daoSa.insert(sa)) {
            if (!txtIdSa.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "No es necesario poner el ID de salida, el sistema lo asigna automáticamente");
            }
            JOptionPane.showMessageDialog(null, "Salida Registrada");
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo registrar la Salida");
        }

        } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al completar datos desde 'entradas': " + e.getMessage());
        }
        limpiarCamposSa();
        limpiarTablaSalidas();
        listarSalidas();
    }//GEN-LAST:event_btnGuardarSActionPerformed

    private void tblSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSalidaMouseClicked
        int fila = tblSalida.getSelectedRow();
        txtIdSa.setText(tblSalida.getValueAt(fila, 0).toString());
        txtIdUs.setText(tblSalida.getValueAt(fila, 1).toString());
        txtIdP.setText(tblSalida.getValueAt(fila, 2).toString());
        txtCan.setText(tblSalida.getValueAt(fila, 4).toString());        
        txtFe.setText(tblSalida.getValueAt(fila, 6).toString());
        cboM.setSelectedItem(tblSalida.getValueAt(fila, 7).toString());
    }//GEN-LAST:event_tblSalidaMouseClicked

    private void btnEditarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarSActionPerformed
        int fila = tblSalida.getSelectedRow();
        //validar la fecha
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        
        if(fila==-1){
            JOptionPane.showMessageDialog(null, "Seleccione un producto");
        }else{
            sa.setId_salida(Integer.parseInt(txtIdSa.getText()));
            sa.setId_usuario(Integer.parseInt(txtIdUs.getText()));
            sa.setId_producto(Integer.parseInt(txtIdP.getText()));
            sa.setCantidad(Integer.parseInt(txtCan.getText()));
            sa.setFecha_salida(LocalDate.parse(txtFe.getText(),formatter));
            sa.setMotivo_salida(cboM.getSelectedItem().toString());
            
            if(daoSa.editar(sa)){
                JOptionPane.showMessageDialog(null, "Se modifico con exito");
                limpiarCamposSa();
                limpiarTablaSalidas();
                listarSalidas();
            }
        }
    }//GEN-LAST:event_btnEditarSActionPerformed

    void limpiarCamposSa(){
        txtIdSa.setText("");
        txtIdUs.setText("");
        txtIdP.setText("");
        
        txtCan.setText("");
        
        txtFe.setText("");
        cboM.setSelectedItem("");
        
    }
    void limpiarTablaSalidas(){
        for(int i=0; i<modeloSalida.getRowCount();i++){
            modeloSalida.removeRow(i);
            i = 0-1;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconDos btnBuscarS;
    private RSMaterialComponent.RSButtonMaterialIconDos btnEditarS;
    private RSMaterialComponent.RSButtonMaterialIconDos btnEliminarS;
    private RSMaterialComponent.RSButtonMaterialIconDos btnGuardarS;
    private javax.swing.JComboBox<String> cboM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSalida;
    private javax.swing.JTextField txtCan;
    private javax.swing.JTextField txtFe;
    private javax.swing.JTextField txtIdP;
    private javax.swing.JTextField txtIdSa;
    private javax.swing.JTextField txtIdUs;
    // End of variables declaration//GEN-END:variables
}
